--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\OluwasegunOjeyinka\PycharmProjects\AdminELPortal\testScripts\base_test.py", line 32, in login
    wait.until(EC.visibility_of_element_located((By.ID, "email")))
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 138, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
	GetHandleVerifier [0x0x3bfe83+66515]
	GetHandleVerifier [0x0x3bfec4+66580]
	(No symbol) [0x0x1adc48]
	(No symbol) [0x0x1f8704]
	(No symbol) [0x0x1f8aab]
	(No symbol) [0x0x23f482]
	(No symbol) [0x0x21b214]
	(No symbol) [0x0x23cba7]
	(No symbol) [0x0x21afc6]
	(No symbol) [0x0x1ec2ca]
	(No symbol) [0x0x1ed154]
	GetHandleVerifier [0x0x6173b3+2521347]
	GetHandleVerifier [0x0x612333+2500739]
	GetHandleVerifier [0x0x3e7cd4+229924]
	GetHandleVerifier [0x0x3d8238+165768]
	GetHandleVerifier [0x0x3deced+193085]
	GetHandleVerifier [0x0x3c8198+100072]
	GetHandleVerifier [0x0x3c8330+100480]
	GetHandleVerifier [0x0x3b25ea+11066]
	BaseThreadInitThunk [0x0x762b5d49+25]
	RtlInitializeExceptionChain [0x0x7776d1ab+107]
	RtlGetAppContainerNamedObjectPath [0x0x7776d131+561]
	(No symbol) [0x0]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\logging\__init__.py", line 1153, in emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u274c' in position 32: character maps to <undefined>
Call stack:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Scripts\pytest.exe\__main__.py", line 6, in <module>
    sys.exit(console_main())
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\config\__init__.py", line 175, in main
    ret: ExitCode | int = config.hook.pytest_cmdline_main(config=config)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 336, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 289, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 343, in _main
    config.hook.pytest_runtestloop(session=session)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\main.py", line 367, in pytest_runtestloop
    item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 117, in pytest_runtest_protocol
    runtestprotocol(item, nextitem=nextitem)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 136, in runtestprotocol
    reports.append(call_and_report(item, "call", log))
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 245, in call_and_report
    call = CallInfo.from_call(
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 344, in from_call
    result: TResult | None = func()
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 246, in <lambda>
    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\runner.py", line 178, in pytest_runtest_call
    item.runtest()
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 1671, in runtest
    self.ihook.pytest_pyfunc_call(pyfuncitem=self)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_hooks.py", line 512, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\pluggy\_callers.py", line 121, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\OluwasegunOjeyinka\AppData\Local\Programs\Python\Python313\Lib\site-packages\_pytest\python.py", line 157, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "C:\Users\OluwasegunOjeyinka\PycharmProjects\AdminELPortal\testScripts\test_T01Login.py", line 21, in test_login
    self.login(self.elportal)
  File "C:\Users\OluwasegunOjeyinka\PycharmProjects\AdminELPortal\testScripts\base_test.py", line 51, in login
    self.logger.error("❌ Login failed: Timeout waiting for login elements or dashboard to load.")
Message: '❌ Login failed: Timeout waiting for login elements or dashboard to load.'
Arguments: ()
